### ISSUE TITLE
Setting global defaults for styles

### ISSUE THREAD

**Issue by GetPsyched** [isac-nitkkr/node-modules#50]
- Font
- Font size
- Colour palette

All this will be set in `tailwind.config.ts`. Refer these values from Figma.

**Comment by SilentJungle399** [comment]
Are these to be taken as labels for font sizes? So it'll be like `text-display`, `text-h1`, ... for font size classes

![image](https://github.com/isac-nitkkr/node-modules/assets/75272148/83d8a98a-aa94-4b7e-a538-13f99280129c)

**Comment by GetPsyched** [comment]
> Are these to be taken as labels for font sizes? So it'll be like `text-display`, `text-h1`, ... for font size classes

Yeah, sounds good.
