### ISSUE TITLE
Sample SQL queries

### ISSUE THREAD

**Issue by SaketRaman2002** [isac-nitkkr/node-modules#60]
Write Sql queries to add sample data in the database .
Schema is pushed in the code

**Comment by aryansri-19** [comment]
Provide some sample data as I am unaware of some columns such as permissions, programs and many such fields. Also, should make i separate file for sql queries?

**Comment by GetPsyched** [comment]
> Provide some sample data as I am unaware of some columns such as permissions, programs and many such fields.

Will keep a call with you to explain things

> Also, should make i separate file for sql queries?

Yes, in the `database/` folder

> And while using Prisma, what is the database url for where its hosted?

Run the command `npm run database:up` to start a local db on which you can create the data.

**Comment by GetPsyched** [comment]
> Shouldn't it be CREATE TABLE <schema_name>.<table_name> Because else, it creates all the tables in the public schema

cc @SaketRaman2002

**Comment by SaketRaman2002** [comment]
> Sure, and one more thing: Shouldn't it be CREATE TABLE <schema_name>.<table_name> Because else, it creates all the tables in the public schema

yep it should be like this only  and will explain the examples on call and will check this also
